namespace:
  name: prod

AppName: techtrends

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: heppiedoc/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

container:
  port: 3111
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
