namespace:
  name: staging

AppName: techtrends

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: heppiedoc/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

container:
  port: 3111
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
